url: "https://cleonwong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/cleonwong-site" # the subpath of your site, e.g. /blog
title: cleon wong # Name of the site.
# source: "src" # Source folder to build the site from.
sass:
  sass_dir: _sass

# Socials:
github_username: CleonWong
linkedin_username: cleonwong
medium_username: cleonwong
behance_username: cleonwong
twitter_username: CleonW_

# Jekyll Collections:
collections:
  pages: # Pages to show on the home page.
    output: true # Set to render files in _pages folder
    permalink: /:title/ # Set the format of the permalink by default
